### PR TITLE
Change folder names

### PR DESCRIPTION
**Pull request by calebwebster**
Please review this PR, which will change the names of two folders.

### CODE REVIEW

**Review by Haiqiangwang21 — APPROVED** [review]
Looks fine

**Comment by calebwebster** [comment]
[Change folder names](https://trello.com/c/AEwrHafw/26-change-folder-names)

**Review by aidenlignieres — APPROVED** [review]
Don't forget to add the command lines for how to add the GitHub repo and rename it, otherwise, it is easy to understand, also add a comment on what has changed when updating the database dump

**Comment by gauvansantiago** [comment]
thank you

**Pull request merged**
