### PR TITLE
Sql Formatter

### PR DESCRIPTION
**Pull request by calebwebster**
This pull request will initialize repository as a npm package and add the sql-formatter npm package as a dependency.

The purpose of this pull request is to help us better resolve database dump conflicts by transforming the database into a readable format. This operation will be done automatically via a GitHub action.

### CODE REVIEW

**Comment by aidenlignieres** [comment]
Looks good so far, just notice that I am seeing a conflict between files, is this supposed to happen? (.github/workflows/format-sql.yml)

**Comment by calebwebster** [comment]
Yea, I'll fix that locally.

**Review by aidenlignieres — APPROVED** [review]
The GitHub action is working great just the conflict between branches needs to be fixed.

**Comment by calebwebster** [comment]
[Testing ways to merge sql dumps](https://trello.com/c/PVOcwrEp/55-testing-ways-to-merge-sql-dumps)

**Pull request merged**
